from __future__ import annotations

from enum import Enum
from typing import Any, Final, NotRequired, TypedDict


class ErrorCode(str, Enum):
    """Stable API error codes for frontend localization."""

    LOCALE_INVALID = "LOCALE_INVALID"
    INPUT_INVALID_JSON = "INPUT_INVALID_JSON"
    INPUT_VALIDATION = "INPUT_VALIDATION"
    INPUT_BAD_FIELD = "INPUT_BAD_FIELD"
    INPUT_UNKNOWN_KEYS = "INPUT_UNKNOWN_KEYS"
    INPUT_PAGINATION = "INPUT_PAGINATION"
    RUN_NOT_FOUND = "RUN_NOT_FOUND"
    RUN_ARTIFACT_NOT_FOUND = "RUN_ARTIFACT_NOT_FOUND"
    RUN_ARTIFACT_TOO_LARGE = "RUN_ARTIFACT_TOO_LARGE"
    RUN_ARTIFACT_INVALID = "RUN_ARTIFACT_INVALID"
    RUN_ID_INVALID = "RUN_ID_INVALID"
    INSTALL_INVALID_MANIFEST = "INSTALL_INVALID_MANIFEST"
    PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
    PROVIDER_TRANSPORT = "PROVIDER_TRANSPORT"
    PROVIDER_HTTP = "PROVIDER_HTTP"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    LOOPBACK_DENIED = "LOOPBACK_DENIED"
    RATE_LIMITED = "RATE_LIMITED"
    REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
    STORAGE_REVIEW_DB = "STORAGE_REVIEW_DB"
    STORAGE_USAGE_DB = "STORAGE_USAGE_DB"
    STORAGE_FS = "STORAGE_FS"
    LOCK_CONFLICT = "LOCK_CONFLICT"
    GRAPH_NODE_LIMIT = "GRAPH_NODE_LIMIT"
    LESSON_LEVEL_INVALID = "LESSON_LEVEL_INVALID"
    EXPORT_FORMAT_UNSUPPORTED = "EXPORT_FORMAT_UNSUPPORTED"
    FEATURE_UNAVAILABLE = "FEATURE_UNAVAILABLE"
    NOT_FOUND = "NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"


ERROR_STATUS: Final[dict[ErrorCode, int]] = {
    ErrorCode.LOCALE_INVALID: 400,
    ErrorCode.INPUT_INVALID_JSON: 400,
    ErrorCode.INPUT_VALIDATION: 422,
    ErrorCode.INPUT_BAD_FIELD: 400,
    ErrorCode.INPUT_UNKNOWN_KEYS: 400,
    ErrorCode.INPUT_PAGINATION: 400,
    ErrorCode.RUN_NOT_FOUND: 404,
    ErrorCode.RUN_ARTIFACT_NOT_FOUND: 404,
    ErrorCode.RUN_ARTIFACT_TOO_LARGE: 413,
    ErrorCode.RUN_ARTIFACT_INVALID: 400,
    ErrorCode.RUN_ID_INVALID: 400,
    ErrorCode.INSTALL_INVALID_MANIFEST: 400,
    ErrorCode.PROVIDER_NOT_FOUND: 404,
    ErrorCode.PROVIDER_TRANSPORT: 502,
    ErrorCode.PROVIDER_HTTP: 502,
    ErrorCode.AUTH_REQUIRED: 401,
    ErrorCode.LOOPBACK_DENIED: 403,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.REQUEST_TIMEOUT: 408,
    ErrorCode.STORAGE_REVIEW_DB: 500,
    ErrorCode.STORAGE_USAGE_DB: 500,
    ErrorCode.STORAGE_FS: 500,
    ErrorCode.LOCK_CONFLICT: 409,
    ErrorCode.GRAPH_NODE_LIMIT: 413,
    ErrorCode.LESSON_LEVEL_INVALID: 400,
    ErrorCode.EXPORT_FORMAT_UNSUPPORTED: 400,
    ErrorCode.FEATURE_UNAVAILABLE: 501,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.INTERNAL_ERROR: 500,
}


class ErrorPayload(TypedDict):
    error_code: str
    error: str
    status: int
    details: NotRequired[dict[str, Any]]


__all__ = ["ERROR_STATUS", "ErrorCode", "ErrorPayload"]
