import { useCallback, useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { Accordion, Alert, Badge, Button, Drawer, Radio, Textarea } from '@mantine/core';
import { useMediaQuery } from '@mantine/hooks';
import { ArrowRight, BookOpen, Check, ChevronLeft, Copy, FileText, Lightbulb, MessageCircle, Send, CircleHelp, PanelsTopLeft, Code2, GitBranch, ExternalLink, Info, X } from 'lucide-react';
import { getKnowledgeCard, streamKnowledgeChat, knowledgeSend, normalizeConversation, type KnowledgeDetail, type KnowledgeMessage, type Stage } from '../api/knowledge';
import { LearningPath, MarkMenu } from './KnowledgeWorkspace';
import KnowledgeCode from './KnowledgeCode';
const LABELS:Record<Stage,string>={front:'卡片正面',back:'卡片背面',understanding:'理解检查',understanding_explanation:'理解题解析',prediction:'结果预测',prediction_explanation:'预测题解析',completed:'学习完成'};
function StudySparkle({size=28,className}:{size?:number;className?:string}){return <svg width={size} height={size} className={className} viewBox="0 0 28 28" aria-hidden="true"><path fill="currentColor" d="M14 3c1.2 7.2 3.8 9.8 11 11-7.2 1.2-9.8 3.8-11 11C12.8 17.8 10.2 15.2 3 14c7.2-1.2 9.8-3.8 11-11Z"/><circle fill="currentColor" cx="5" cy="4" r="1.5"/><circle fill="currentColor" cx="24" cy="24" r="1.2"/></svg>;}
function PineAvatar(){return <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 21V11M12 13C6 13 3 10 3 5C9 5 12 7 12 13ZM12 11C12 6 16 3 21 3C21 9 18 12 12 12"/></svg>;}
export default function KnowledgeStudy({cardId,providerName,bindingId,onChanged}:{cardId:string;providerName:string;bindingId:string;onChanged:()=>Promise<void>}) {
  const [params,setParams]=useSearchParams(); const [detail,setDetail]=useState<KnowledgeDetail|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [aiOpen,setAiOpen]=useState(false);const compact=useMediaQuery('(max-width:1250px)');
  const [selection,setSelection]=useState('');const [note,setNote]=useState('');const [chat,setChat]=useState('');const [chatBusy,setChatBusy]=useState(false);const [chatError,setChatError]=useState('');const [history,setHistory]=useState<KnowledgeMessage[]>([]);const [reviewSide,setReviewSide]=useState<Stage|null>(params.get('revisit')?'front':null);
  const [materialPreview,setMaterialPreview]=useState<{approval_hash:string;payload_text:string;provider_host:string;model_name:string}|null>(null);
  const pending=useRef<Record<string,string>>({});const chatRun=useRef(0);const chatController=useRef<AbortController|null>(null);const chatAttempt=useRef<{key:string;body:Record<string,unknown>}|null>(null);const chatMessages=useRef<HTMLDivElement>(null);const followChat=useRef(true);const [streaming,setStreaming]=useState<{message:string;text:string;status:'streaming'|'stopped'|'failed'}|null>(null);
  useEffect(()=>()=>{chatRun.current++;chatController.current?.abort();},[]);
  const path='/cards/'+encodeURIComponent(cardId);
  const refresh=useCallback(async()=>{const next=await getKnowledgeCard(cardId);setDetail(next);setNote(next.learning.note_text??'');setHistory(next.conversation??[]);return next;},[cardId]);
  useEffect(()=>{setDetail(null);setError('');void refresh().catch(e=>setError(String(e)));},[refresh]);
  const stage=reviewSide??detail?.learning.stage??'front';const kind=stage.startsWith('prediction')?'prediction':'understanding';const question=detail?.questions?.find(q=>q.kind===kind);const answer=detail?.learning.answers?.[kind];const explanation=stage.endsWith('_explanation');const learning=['front','back'].includes(stage);
  useEffect(()=>{setSelection(question?(detail?.learning.option_drafts?.[question.question_id]??answer?.option_id??''):'');},[question?.question_id,question?.version,detail?.learning.option_drafts,answer?.option_id]);
  async function act(fn:()=>Promise<unknown>) {setBusy(true);setError('');try{await fn();await refresh();await onChanged();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  function requestId(key:string){return pending.current[key]??(pending.current[key]=crypto.randomUUID());}
  function changeStage(next:Stage){if(reviewSide){setReviewSide(next);return;}void act(()=>knowledgeSend(path+'/learning',{stage:next},'PUT'));}
  async function choose(option:string){setSelection(option);try{await knowledgeSend(path+'/learning',{option_drafts:{[question!.question_id]:option}},'PUT');}catch(e){setError('选项草稿保存失败，可重试提交。'+String(e));}}
  async function send(message=chat,retry=false){
    if(!message.trim()||chatController.current)return;
    const controller=new AbortController();chatController.current=controller;
    const run=++chatRun.current;followChat.current=true;setChatBusy(true);setChatError('');setStreaming({message,text:'',status:'streaming'});
    const key=retry&&chatAttempt.current?chatAttempt.current.key:'chat:'+detail?.card.card_version+':'+stage+':'+question?.question_id+':'+message;
    const body=retry&&chatAttempt.current?chatAttempt.current.body:{request_id:requestId(key),provider_name:providerName,message,stage,question_id:learning?null:question?.question_id};chatAttempt.current={key,body};
    try {
      const response=await streamKnowledgeChat(cardId,body,controller.signal,delta=>{
        if(run===chatRun.current)setStreaming(current=>current?{...current,text:current.text+delta}:current);
      });
      if(run===chatRun.current){setHistory(normalizeConversation(response.conversation));setStreaming(null);setChat(current=>current===message?'':current);delete pending.current[key];chatAttempt.current=null;}
    }catch(e){
      if(run===chatRun.current){setStreaming(current=>current?{...current,status:controller.signal.aborted?'stopped':'failed'}:current);if(!controller.signal.aborted)setChatError(String(e));}
    }finally{if(run===chatRun.current){setChatBusy(false);chatController.current=null;}}
  }
  function stopChat(){const controller=chatController.current;if(!controller)return;chatRun.current++;controller.abort();chatController.current=null;setChatBusy(false);setStreaming(current=>current?{...current,status:'stopped'}:current);}
  useEffect(()=>{if(followChat.current&&chatMessages.current)chatMessages.current.scrollTop=chatMessages.current.scrollHeight;},[streaming?.text,streaming?.status,history]);
  const sourceBars=<div className="knowledge-source-bars">{detail?.sources.length?detail.sources.map(source=><div className="knowledge-source-bar" key={source.source_ref_id??source.commit_sha}><span title={source.relative_path}>来源：{source.project_name||source.relative_path||source.commit_title} · <code>{source.commit_sha?.slice(0,7)||'工作区证据'}</code></span><Button component={Link} to={'/growth?view=projects&commit='+(source.commit_sha??'')+'&source='+source.source_ref_id} variant="default" leftSection={<ExternalLink size={18}/>}>查看提交与代码</Button></div>):<p>当前未关联可读取证据，请在项目与提交中核对来源。</p>}</div>;
  const evidence=learning?sourceBars:kind==='prediction'&&!explanation?<details className="knowledge-predict-evidence"><summary>查看题目依据</summary>{sourceBars}</details>:<Accordion className="knowledge-question-evidence" variant="contained"><Accordion.Item value="question-evidence"><Accordion.Control icon={<FileText size={22}/>}>本题依据 · {detail?.card.title}</Accordion.Control><Accordion.Panel>{sourceBars}</Accordion.Panel></Accordion.Item></Accordion>;
  const ai=<aside className={'knowledge-paper knowledge-ai'+(stage==='back'?' knowledge-ai--back':'')+(history.length<=1&&!streaming?' is-welcome':'')+(!learning?' knowledge-ai--question':'')+(kind==='prediction'&&!learning?' knowledge-ai--prediction':'')+(explanation?' knowledge-ai--explanation':'')}><header>{!learning&&(kind==='prediction'?<span className="knowledge-message-icon knowledge-ai-avatar"><PineAvatar/></span>:<StudySparkle className="knowledge-ai-star" size={28}/>)}<h2>{explanation?'AI 助手（当前卡片）':'AI 助手'}</h2>{kind==='prediction'&&!learning&&<p className="knowledge-ai-header-description">{explanation?'基于当前卡片、题目和代码证据，帮助你理解。':'自动携带当前卡片、题目与代码证据，提供针对性解答'}</p>}<Badge color="pine">聊天仅辅助理解，不参与判分。</Badge></header>{learning&&stage==='back'?<div className="knowledge-ai-back-context"><h3>当前上下文</h3><div><Badge>{cardId.slice(0,12)}</Badge><Badge>卡片背面</Badge><Badge>当前代码证据</Badge></div><Accordion variant="contained"><Accordion.Item value="back-context"><Accordion.Control icon={<FileText size={20}/>}>自动携带当前卡片与证据</Accordion.Control><Accordion.Panel>{detail?.sources.map(source=><p key={source.source_ref_id}>{source.relative_path} · {source.commit_sha?.slice(0,7)}</p>)}</Accordion.Panel></Accordion.Item></Accordion></div>:learning?<Accordion defaultValue="context" variant="contained"><Accordion.Item value="context"><Accordion.Control>当前上下文</Accordion.Control><Accordion.Panel><dl><div><dt><PanelsTopLeft size={20}/>当前卡片</dt><dd><Badge>{cardId.slice(0,12)}</Badge></dd></div><div><dt><FileText size={20}/>{LABELS[stage]}</dt><dd>{detail?.card.title}</dd></div><div><dt><Code2 size={20}/>当前代码证据</dt><dd title={detail?.sources[0]?.relative_path}>{detail?.sources[0]?.relative_path||`${detail?.sources.length??0} 项`}</dd></div><div><dt><GitBranch size={20}/>自动携带当前卡片与证据</dt><dd>{detail?.sources[0]?.commit_sha?.slice(0,7)||'未关联提交'}</dd></div></dl></Accordion.Panel></Accordion.Item></Accordion>:<div className="knowledge-ai-question-context"><div><Badge>{cardId.slice(0,8)}</Badge><Badge color="blue">{kind==='understanding'?'理解题 Q1':'预测题 Q2'} · v{question?.version}</Badge><Badge color="gray">{answer?'已提交 · 解析':'未提交'}</Badge></div><p>自动携带当前卡片、题目与 {detail?.sources.length??0} 项代码证据</p></div>}
  <div className="knowledge-ai-messages" ref={chatMessages} onScroll={e=>{const node=e.currentTarget;followChat.current=node.scrollHeight-node.scrollTop-node.clientHeight<80;}} aria-live="polite">{history.length===0&&!streaming?<div className="knowledge-message"><span className="knowledge-message-icon">{learning||kind==="prediction"?<PineAvatar/>:<StudySparkle size={27}/>}</span><div><strong>AI</strong><p>对题目或代码有疑问，可以直接问我。你也可以随时翻面查看讲解。</p></div></div>:history.map((message,i)=><div key={i} className={'knowledge-message '+(message.role==='user'?'is-user':'')}><span className="knowledge-message-icon">{message.role==='user'?'我':learning||kind==="prediction"?<PineAvatar/>:<StudySparkle size={27}/>}</span><div><small className={!message.stage&&!message.question_id&&!message.created_at?"is-identity-only":undefined}>{message.stage?LABELS[message.stage as Stage]:message.role==='user'?(message.created_at?'':'我'):(explanation&&message.created_at?'':'AI')}{message.question_id?' · '+message.question_id.slice(0,8):''}{message.created_at&&!Number.isNaN(Date.parse(message.created_at))&&<time dateTime={message.created_at} title={new Date(message.created_at).toLocaleString()}>{new Date(message.created_at).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false})}</time>}</small><p>{message.content_text??message.content}</p></div></div>)}{streaming&&<><div className="knowledge-message is-user"><span className="knowledge-message-icon">我</span><div><p>{streaming.message}</p></div></div><div className="knowledge-message"><span className="knowledge-message-icon">{learning||kind==="prediction"?<PineAvatar/>:<StudySparkle size={27}/>}</span><div><small>{streaming.status==='streaming'?'AI 正在回复':streaming.status==='stopped'?'已停止 · 可重试并核对记录':'回复未完成'}</small><p>{streaming.text||(streaming.status==='streaming'?'正在等待模型输出…':streaming.status==='stopped'?'请求已停止，输入仍然保留。':'尚未收到回复，可重试这次提问。')}</p>{streaming.status!=='streaming'&&<Button size="compact-sm" variant="subtle" onClick={()=>void send(streaming.message,true)}>重试这次提问</Button>}</div></div></>}</div>
  <div className="knowledge-ai-quick"><strong>{answer?"你可以继续问":"快捷提问"}</strong><div>{(learning?(stage==='front'?['解释题目条件','解释这段代码']:['换个例子','展开边界条件']):answer?['解释我的误区','换个条件再推演','回到相关知识']:kind==='prediction'?['梳理题目条件！','提示第一步','解释 API']:['解释题目条件','给我一个提示','回顾相关知识']).map(text=><Button key={text} variant="default" disabled={chatBusy||!providerName} leftSection={!learning&&!answer&&kind==="understanding"?(text==="解释题目条件"?<Lightbulb size={22}/>:text==="给我一个提示"?<CircleHelp size={22}/>:<BookOpen size={22}/>):undefined} onClick={()=>void send(text)}>{text}</Button>)}</div></div>{chatError&&<Alert color="red">{chatError}，输入已保留，可再次发送。</Alert>}{!providerName&&<Alert color="gray">尚未配置模型，可继续学习和客观作答。<Link to="/settings">配置模型</Link></Alert>}
  <form className="knowledge-ai-compose" onSubmit={e=>{e.preventDefault();void send();}}><Textarea aria-label="向 AI 提问" placeholder={learning?"输入疑问，围绕当前内容继续聊…":"继续提问…"} value={chat} maxLength={1000} onChange={e=>setChat(e.target.value)} minRows={4}/><div><small>{chat.length}/1000</small>{chatBusy?<Button type="button" variant="default" onClick={stopChat}>停止回复</Button>:<Button type="submit" disabled={!chat.trim()||!providerName} rightSection={<Send size={16}/>}>发送</Button>}</div></form>{kind==='prediction'&&!learning&&<small className="knowledge-ai-footnote">聊天仅辅助理解，不参与判分。</small>}</aside>;
  const materialSetup=detail?.questions.length===0?<div className="knowledge-paper knowledge-material-setup"><h2>先生成知识讲解与两道检查题</h2><p>结合这张卡片的真实提交证据，准备正反面讲解、理解题和结果预测题。</p>{!providerName?<Alert color="orange">请先在设置中配置可用模型。<Link to="/settings">配置模型</Link></Alert>:<Button loading={busy} onClick={()=>void act(async()=>{setMaterialPreview(await knowledgeSend(path+'/materials/preview',{provider_name:providerName,binding_id:bindingId}));})}>预览材料生成范围</Button>}{materialPreview&&<><Alert>将发送到 {materialPreview.provider_host} · {materialPreview.model_name}</Alert><details><summary>核对来源与发送内容</summary><pre className="knowledge-scenario">{materialPreview.payload_text}</pre></details><Button loading={busy} onClick={()=>void act(async()=>{await knowledgeSend(path+'/materials',{provider_name:providerName,binding_id:bindingId,approved_payload_hash:materialPreview.approval_hash,approved:true});setMaterialPreview(null);})}>确认并生成知识讲解与两题</Button></>}</div>:null;
  if(!detail)return <div className="knowledge-paper"><p role={error?'alert':'status'}>{error||'正在加载卡片与学习进度…'}</p>{error&&<Button onClick={()=>void act(refresh)}>重试</Button>}</div>;
  const active=stage==='completed'?3:stage.startsWith('prediction')?2:stage.startsWith('understanding')?1:0;
  const excerpt=detail.sources.find(source=>source.excerpt)?.excerpt;
  return <div className={'knowledge-study'+(stage==='front'?' is-front':stage==='back'?' is-back':'')+(kind==='understanding'&&!learning&&!explanation?' is-understanding':'')+(kind==='prediction'&&!learning?' is-prediction':'')+(explanation?' is-explanation':'')}><div className="knowledge-study-main"><div className="knowledge-study-title"><Link to={(()=>{const next=new URLSearchParams(params);next.delete('card');next.delete('revisit');next.set('view','cards');return '/growth?'+next;})()}><ChevronLeft size={18}/>{explanation?detail.card.title:kind==='prediction'&&!learning?'结果预测':'知识卡'}{explanation&&<Badge className="knowledge-title-id" color="pine">{cardId.slice(0,8)}</Badge>}</Link>{kind==='prediction'&&!learning&&!explanation&&<p className="knowledge-study-origin">{cardId.slice(0,12)} · {detail.card.title}</p>}{explanation&&<p className="knowledge-study-origin">来源：{detail.sources[0]?.project_name||detail.sources[0]?.relative_path||'关联项目'} · 代表性提交 {detail.sources.find(source=>source.commit_sha)?.commit_sha?.slice(0,8)??'关联提交证据'}</p>}{compact&&<Button variant="default" leftSection={<MessageCircle size={18}/>} onClick={()=>setAiOpen(true)}>问 AI</Button>}</div><LearningPath active={active}/>{error&&<Alert color="red" title="操作未完成">{error}</Alert>}
  {materialSetup}<article className="knowledge-paper knowledge-study-card">{explanation&&<div className="knowledge-explanation-tabs"><button aria-pressed={kind==="understanding"} disabled={!detail.learning.answers.understanding} onClick={()=>detail.learning.stage==="completed"?setReviewSide("understanding_explanation"):changeStage("understanding_explanation")}>理解题解析</button><button aria-pressed={kind==="prediction"} disabled={!detail.learning.answers.prediction} onClick={()=>detail.learning.stage==="completed"?setReviewSide("prediction_explanation"):changeStage("prediction_explanation")}>结果预测解析</button></div>}{learning&&<Badge color="pine" className="knowledge-side-label" leftSection={stage==='back'?<BookOpen size={22}/>:undefined}>{stage==='front'?'正面 · 先想一想':'背面 · 知识讲解'}</Badge>}<div className="knowledge-study-meta"><Badge size="lg">{cardId.slice(0,12)}{!learning&&` · ${detail.card.title}`}</Badge><MarkMenu card={detail.card} onChanged={()=>void refresh()}/></div>
  {learning?<><h2>{detail.card.title}</h2>{stage==='back'&&<p className="knowledge-back-origin">来源：{detail.sources[0]?.project_name||detail.sources[0]?.relative_path||'关联代码证据'}</p>}<h3 className="knowledge-core-question" data-long={detail.card.front_question.length>60||undefined}>{detail.card.front_question}</h3>{stage==='front'&&detail.card.material?.front_context&&<p className="knowledge-front-context">{detail.card.material.front_context}</p>}{excerpt&&<div className="knowledge-code"><header><strong>教学片段</strong><Button variant="subtle" size="compact-sm" leftSection={<Copy size={14}/>} onClick={()=>void navigator.clipboard.writeText(excerpt)}>复制代码</Button></header><KnowledgeCode text={excerpt}/></div>}{stage==='back'&&<><div className="knowledge-core-explanation"><Lightbulb size={27}/><h3>核心解释</h3><p>{detail.card.material?.back_summary||detail.card.back_answer||'讲解材料尚未准备完成，请稍后重试。'}</p></div><Accordion className="knowledge-mechanisms" defaultValue="mechanism" variant="contained"><Accordion.Item value="mechanism"><Accordion.Control icon={<span className="knowledge-section-number">1</span>}>核心机制</Accordion.Control><Accordion.Panel><div className="knowledge-prose">{detail.card.material?.back_mechanism||detail.card.back_explanation||'暂无补充讲解。'}</div></Accordion.Panel></Accordion.Item><Accordion.Item value="boundary"><Accordion.Control icon={<span className="knowledge-section-number">2</span>}>适用边界</Accordion.Control><Accordion.Panel><div className="knowledge-prose">{detail.card.material?.back_boundary}</div></Accordion.Panel></Accordion.Item><Accordion.Item value="sources"><Accordion.Control icon={<span className="knowledge-section-number">3</span>}>工程证据 · {detail.sources[0]?.commit_sha?.slice(0,7)||'当前改动'}</Accordion.Control><Accordion.Panel>{evidence}</Accordion.Panel></Accordion.Item><Accordion.Item value="misconceptions"><Accordion.Control icon={<span className="knowledge-section-number">4</span>}>常见误区</Accordion.Control><Accordion.Panel>{detail.card.material?.misconceptions.map((item,i)=><p key={i}>{item}</p>)}</Accordion.Panel></Accordion.Item></Accordion></>}{stage==='front'&&evidence}
  <p className="knowledge-think"><Lightbulb size={23}/>{stage==='front'?'可以先在心里想一想，也可以直接翻面学习。':'理解知识后，再做两道检查题；每题都会展示完整解析。'}</p><div className="knowledge-bottom-actions">{stage==="back"&&<span className="knowledge-back-notice"><Info size={21}/>翻面是学习过程，不计分；理解检查在下一步。</span>}<Button variant="default" onClick={()=>stage==='front'?setParams(p=>{const n=new URLSearchParams(p);n.delete('card');return n;}):changeStage('front')}>{stage==='front'?'稍后继续':'返回正面'}</Button>{stage==='front'?<Button loading={busy} rightSection={<ArrowRight size={18}/>} onClick={()=>reviewSide?setReviewSide('back'):void act(()=>knowledgeSend(path+'/flip'))}>翻面看讲解</Button>:reviewSide?<Button onClick={()=>setReviewSide(null)}>查看学习记录</Button>:<Button loading={busy} disabled={!detail.card.back_answer} rightSection={<ArrowRight size={18}/>} onClick={()=>changeStage('understanding')}>进入理解检查</Button>}</div></>:
  stage==='completed'?<div className="knowledge-completed"><span><Check size={36}/></span><h2>这张卡片的首次学习已完成</h2><p>讲解与两题解析已确认。首次作答和个人笔记会保留。</p>{detail.questions.map(q=>{const a=detail.learning.answers[q.kind];return <div className="knowledge-paper" key={q.question_id}><strong>{q.kind==='understanding'?'理解检查':'结果预测'}</strong><p>{q.stem}</p><Badge color={a?.correct?'pine':'orange'}>{a?.correct?'首次作答正确':'首次作答错误，已学习解析'}</Badge><Button variant="subtle" onClick={()=>setReviewSide(q.kind)}>回看题目</Button><Button variant="subtle" onClick={()=>setReviewSide(q.kind+'_explanation' as Stage)}>查看完整解析</Button></div>;})}<div className="knowledge-bottom-actions"><Button variant="default" onClick={()=>setReviewSide('front')}>回看卡片</Button><Button loading={busy} onClick={()=>void act(async()=>{await knowledgeSend(path+'/wiki/draft',{request_id:requestId('wiki')});setParams(p=>{const n=new URLSearchParams(p);n.set('view','wiki');return n;});})}>提炼 Wiki 草稿 <ArrowRight size={18}/></Button></div></div>:
  !question||question.options.length!==4?<Alert color="orange" title="题包需要核对">题目或四个选项尚不完整，请重新生成完整材料后继续。<Button variant="subtle" onClick={()=>void act(refresh)}>重新读取</Button></Alert>:
  <><p className="knowledge-question-label">第 {kind==='understanding'?'1':'2'} 题 · {kind==='understanding'?'机制与边界':'预测运行结果'} · 单选</p>{kind==='prediction'&&!explanation&&excerpt&&<div className="knowledge-code"><header>教学代码 · 根据执行过程推断结果</header><KnowledgeCode text={excerpt}/></div>}{question.scenario&&(kind==='understanding'?<div className="knowledge-scenario knowledge-scenario--prose"><Badge color="gray">场景</Badge><p>{question.scenario}</p></div>:<pre className="knowledge-scenario">{question.scenario}</pre>)}<h2 className="knowledge-question-stem">{question.stem}</h2>
  {explanation&&answer?<><div className={'knowledge-answer-result'+(answer.correct?' is-correct':'')}><Check size={20}/>{answer.correct?'本次回答正确':'已保存首次作答'} · {answer.option_id} · {question.options.find(option=>option.id===answer.option_id)?.text}</div><div className="knowledge-conclusion"><Lightbulb size={25}/><div><h3>核心结论</h3><p>{question.conclusion||question.explanations?.[answer.correct_option_id]||question.reasoning}</p></div></div><section className="knowledge-reasoning"><h3>执行路径</h3>{question.reasoning.split(String.fromCharCode(10)).filter(Boolean).length>1?<ol>{question.reasoning.split(String.fromCharCode(10)).filter(Boolean).map((step,index)=><li key={index}>{step}</li>)}</ol>:<p>{question.reasoning}</p>}</section><div className="knowledge-explanations"><h3>逐项解析</h3>{question.options.map(option=><div key={option.id} className={'knowledge-explanation'+(option.id===answer.correct_option_id?' is-correct':'')}><strong>{option.id} · {option.text}</strong><p>{question.explanations?.[option.id]||'解析尚未加载，请重试。'}</p><span className="knowledge-option-result">{option.id===answer.correct_option_id?<><Check size={18}/>正确</>:<><X size={18}/>不正确</>}</span></div>)}</div><Accordion className="knowledge-explanation-review" defaultValue="review" variant="contained" chevronPosition="left"><Accordion.Item value="review"><Accordion.Control>{kind==='prediction'?'理解题回顾':'适用边界与误区'}</Accordion.Control><Accordion.Panel><p>{kind==='prediction'?detail.questions.find(item=>item.kind==='understanding')?.explanations?.[detail.learning.answers.understanding?.correct_option_id??'']||question.boundary:question.boundary}</p><details><summary>适用边界与代码依据</summary><p>{question.boundary}</p>{sourceBars}</details></Accordion.Panel></Accordion.Item></Accordion><div className="knowledge-bottom-actions"><Button variant="default" onClick={()=>reviewSide?setReviewSide('back'):changeStage('back')}>回到知识学习</Button>{reviewSide?<Button onClick={()=>setReviewSide(null)}>返回学习记录</Button>:<Button loading={busy} disabled={question.options.some(o=>!question.explanations?.[o.id])||!question.reasoning} onClick={()=>void act(async()=>{await knowledgeSend(path+'/explanations/'+question.question_id+'/confirm',{request_id:requestId('explanation:'+question.question_id)});if(kind==='prediction')await knowledgeSend(path+'/complete');})}>{kind==='understanding'?'我已读完解析，继续结果预测':'我已读完解析，完成学习'}</Button>}{kind==='prediction'&&<small className="knowledge-explanation-next">完成后可整理个人笔记，再生成 Wiki 草稿。右侧对话不改变首次作答记录。</small>}</div></>:
  <><Radio.Group value={selection} onChange={v=>void choose(v)} aria-label={question.stem}><div className="knowledge-options">{question.options.map(option=><Radio key={option.id} value={option.id} label={<span><b>{option.id}.</b> {option.text}</span>} disabled={busy||!!answer}/>)}</div></Radio.Group><p className="knowledge-muted knowledge-answer-status"><Badge color="gray">{answer?"已提交 · 回看":"尚未提交"}</Badge> {kind!=='prediction'&&(answer?"已保留首次作答，可回看完整解析。":"提交后查看答案、各选项原因与适用边界。")}</p>{evidence}<div className="knowledge-bottom-actions"><Button variant="default" onClick={()=>changeStage('back')}>返回知识学习</Button><Button loading={busy} disabled={!selection||!!answer} onClick={()=>void act(()=>knowledgeSend(path+'/answers',{request_id:requestId('answer:'+question.question_id+':'+selection),question_id:question.question_id,version:question.version,option_id:selection}))}>{answer?"已保存首次作答":"提交答案"}</Button>{answer&&<Button onClick={()=>setReviewSide(kind+"_explanation" as Stage)}>查看本题解析</Button>}</div></>}</>}
  <Accordion className="knowledge-notes" variant="contained"><Accordion.Item value="notes"><Accordion.Control icon={<BookOpen size={18}/>}>个人笔记（不参与判分）</Accordion.Control><Accordion.Panel><Textarea aria-label="个人笔记" value={note} onChange={e=>setNote(e.target.value)} minRows={4} placeholder="用自己的话留下理解，不作为第三道题。"/><Button variant="default" loading={busy} onClick={()=>void act(()=>knowledgeSend(path+'/note',{text:note},'PUT'))}>保存笔记</Button></Accordion.Panel></Accordion.Item></Accordion>
  </article></div>{!compact&&ai}<Drawer opened={aiOpen} onClose={()=>setAiOpen(false)} position="right" size={460} title="AI 速问" returnFocus>{ai}</Drawer></div>;
}
